FROM amazon/opendistro-for-elasticsearch:1.13.2

COPY --chown=elasticsearch:elasticsearch .docker/elasticsearch/config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
